//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAutomoviles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transporte_auto
    {
        public Nullable<int> NumLote { get; set; }
        public string FolioAuto { get; set; }
        public int id { get; set; }
    
        public virtual Automovil Automovil { get; set; }
        public virtual Solicitud_de_transporte Solicitud_de_transporte { get; set; }
    }
}
